export { Footer } from './Footer/Footer';
export { SocialMediaComponent } from './SocialMediaComponent/SocialMediaComponent';
export { TeamCard} from './TeamCard/TeamCard';
export { Navbar } from './Navbar/Navbar';
export { PropertiesSection } from './PropertiesSection/PropertiesSection';
export { PropertiesCard } from './PropertiesCard/PropertiesCard';
export { SocialMediaIcon } from './SocialMediaIcon/SocialMediaIcon';
export { AgentCard } from './AgentCard/AgentCard';
export { ContactAgentsSection } from './ContactAgentsSection/ContactAgentsSection';
export { Service } from './Service/Service';